# Generated by Django 3.0.3 on 2020-08-05 07:09

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, max_length=200, upload_to='%Y/%m/%d/'),
        ),
    ]
